
/**************************************************************
 *	
 *	gameSound0, 8 bit, 11025Hz,
 *	1 channel, 319392 bytes/channel
 *	Total Size: 1 * 319392 + 4 (header) = 319436 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\DKrystine\Documents\GaTech\CS2261\Final Project\Milestone 4\gameSound0.wav
 *	Time-stamp: Tue Apr 11 21:23:30 2017
 *	
 **************************************************************/

#ifndef __GAMESOUND0H__
#define __GAMESOUND0H__

#define GAMESOUND0FREQ 11025
#define GAMESOUND0LEN 319392

extern const unsigned char gameSound0[319392];

#endif /* __GAMESOUND0H__ */
