
/**************************************************************
 *	
 *	gameSound, 8 bit, 11025Hz,
 *	1 channel, 332090 bytes/channel
 *	Total Size: 1 * 332090 + 4 (header) = 332134 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\DKrystine\Documents\GaTech\CS2261\Final Project\Milestone 4\gameSound.wav
 *	Time-stamp: Tue Apr 11 21:44:56 2017
 *	
 **************************************************************/

#ifndef __GAMESOUNDH__
#define __GAMESOUNDH__

#define GAMESOUNDFREQ 11025
#define GAMESOUNDLEN 332090

extern const unsigned char gameSound[332090];

#endif /* __GAMESOUNDH__ */
