
/**************************************************************
 *	
 *	oofSound, 8 bit, 11025Hz,
 *	1 channel, 6632 bytes/channel
 *	Total Size: 1 * 6632 + 4 (header) = 6676 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\DKrystine\Documents\GaTech\CS2261\Final Project\Milestone 3\oofSound.wav
 *	Time-stamp: Mon Apr 03 00:20:38 2017
 *	
 **************************************************************/

#ifndef __OOFSOUNDH__
#define __OOFSOUNDH__

#define OOFSOUNDFREQ 11025
#define OOFSOUNDLEN 6632

extern const unsigned char oofSound[6632];

#endif /* __OOFSOUNDH__ */
