
/**************************************************************
 *	
 *	punching, 8 bit, 11025Hz,
 *	1 channel, 4251 bytes/channel
 *	Total Size: 1 * 4251 + 4 (header) = 4295 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\DKrystine\Documents\GaTech\CS2261\Final Project\Milestone 4 - fightingStuff\punching.wav
 *	Time-stamp: Mon Apr 24 22:40:24 2017
 *	
 **************************************************************/

#ifndef __PUNCHINGH__
#define __PUNCHINGH__

#define PUNCHINGFREQ 11025
#define PUNCHINGLEN 4230

extern const unsigned char punching[4251];

#endif /* __PUNCHINGH__ */
