
/**************************************************************
 *	
 *	titleSong, 8 bit, 11025Hz,
 *	1 channel, 498251 bytes/channel
 *	Total Size: 1 * 498251 + 4 (header) = 498295 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\DKrystine\Documents\GaTech\CS2261\Final Project\Milestone 4\titleSong.wav
 *	Time-stamp: Tue Apr 11 21:09:43 2017
 *	
 **************************************************************/

#ifndef __TITLESONGH__
#define __TITLESONGH__

#define TITLESONGFREQ 11025
#define TITLESONGLEN 498251

extern const unsigned char titleSong[498251];

#endif /* __TITLESONGH__ */
